/**
 * Manual enrollment script — offline/admin use only.
 *
 * Usage:
 *   node_modules/.bin/tsx prisma/enroll.ts <studentEmail> <courseSlug> [enrolledByEmail]
 *
 * Examples:
 *   node_modules/.bin/tsx prisma/enroll.ts student@example.com my-course-slug
 *   node_modules/.bin/tsx prisma/enroll.ts student@example.com my-course-slug admin@example.com
 */

import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';

// eslint-disable-next-line import/no-unresolved -- generated by `prisma generate`, not committed to git
import { PrismaClient } from '../src/generated/client';

const connectionString = process.env.DATABASE_URL;
const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  const [studentEmail, courseSlug, enrolledByEmail] = process.argv.slice(2);

  if (!studentEmail || !courseSlug) {
    console.error(
      '\n❌ Usage: tsx prisma/enroll.ts <studentEmail> <courseSlug> [enrolledByEmail]\n',
    );
    process.exit(1);
  }

  // ── Resolve student ──────────────────────────────────────────────────────
  const student = await prisma.user.findUnique({ where: { email: studentEmail } });
  if (!student) {
    console.error(`\n❌ No user found with email: ${studentEmail}\n`);
    process.exit(1);
  }
  if (student.role !== 'STUDENT') {
    console.warn(
      `\n⚠️  User "${studentEmail}" has role ${student.role}, not STUDENT. Continuing anyway...\n`,
    );
  }

  // ── Resolve course ───────────────────────────────────────────────────────
  const course = await prisma.course.findUnique({ where: { slug: courseSlug } });
  if (!course) {
    console.error(`\n❌ No course found with slug: ${courseSlug}\n`);
    process.exit(1);
  }
  if (course.status !== 'PUBLISHED') {
    console.warn(
      `\n⚠️  Course "${course.title}" is ${course.status} (not PUBLISHED). Continuing anyway...\n`,
    );
  }

  // ── Resolve optional enrolledBy admin ───────────────────────────────────
  let enrolledById: string | null = null;
  if (enrolledByEmail) {
    const admin = await prisma.user.findUnique({ where: { email: enrolledByEmail } });
    if (!admin) {
      console.error(`\n❌ No user found for enrolledBy email: ${enrolledByEmail}\n`);
      process.exit(1);
    }
    enrolledById = admin.id;
  }

  // ── Check for existing enrollment ────────────────────────────────────────
  const existing = await prisma.enrollment.findUnique({
    where: {
      studentUserId_courseId: {
        studentUserId: student.id,
        courseId: course.id,
      },
    },
  });
  if (existing) {
    console.error(
      `\n❌ Student "${studentEmail}" is already enrolled in "${course.title}" (status: ${existing.status})\n`,
    );
    process.exit(1);
  }

  // ── Create enrollment ────────────────────────────────────────────────────
  const enrollment = await prisma.enrollment.create({
    data: {
      studentUserId: student.id,
      courseId: course.id,
      enrolledBy: enrolledById,
      paymentId: null, // offline — no payment gateway involved
      amountPaid: 0,
      status: 'ACTIVE',
    },
  });

  console.log('\n✅ Enrollment created successfully!');
  console.log('─────────────────────────────────');
  console.log(`   Student  : ${student.name} (${student.email})`);
  console.log(`   Course   : ${course.title} (${course.slug})`);
  console.log(`   Status   : ${enrollment.status}`);
  console.log(`   Enrolled : ${enrollment.enrolledAt.toISOString()}`);
  if (enrolledById) {
    console.log(`   By admin : ${enrolledByEmail}`);
  }
  console.log('─────────────────────────────────\n');
}

main()
  .catch((err) => {
    console.error('\n❌ Unexpected error:', err.message ?? err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
